### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by indolering** [namecoin/namecoin.info#13]
We need an SSL cert that's not setting off people's alarms.  

* [List of certs discounts/coupons](http://www.retailmenot.com/s/wildcard+ssl).
* [$60 comodo wildcard cert](https://www.ssl2buy.com/positive-ssl-wildcard.php), use coupon code: `S2B-CW50`.

**Comment by JeremyRand** [comment]
@indolering can we close this as fixed?

**Comment by indolering** [comment]
I'm going to open a new one for better SSL migration.
