### ISSUE TITLE
Lightweight resolver blog post to be published

### ISSUE THREAD

**Issue by hlandau** [namecoin/namecoin.info#87]
Indolering wants this published on the Namecoin project blog:

Namecoin: Lightweight Resolution Roadmap
https://github.com/hlandau/ncdocs/blob/master/lwblogpost.md

**Comment by ryancdotorg** [comment]
I have some edits - will make them this evening.

**Comment by indolering** [comment]
@ryancdotorg I would like to get this published, perhaps you could outline what you wanted changed and I could edit it?

**Comment by phelixbtc** [comment]
Great article. 
 
  > the identity of the set of all current names is attested to continously throughout the mining process"

Something seems to be missing here. 
 

  I would not mention DNSChain. A general warning would be plenty. Also something like it might have it's niche.  
 
  >  Only secure lightweight resolution, as described above, can make Namecoin domains robust against MITM attacks perpetrated by state actors.

Or full nodes. With UTXO and spam removed from the blockchain they would still be pretty lightweight.

**Comment by JeremyRand** [comment]
I support mentioning DNSChain, because it's directly relevant to the advantages of the lightweight resolvers discussed in the post.

**Comment by indolering** [comment]
> > the identity of the set of all current names is attested to continously throughout the mining process"
> Something seems to be missing here. 

No, I think that sounds correct, except "continuously" is spelled incorrectly.

**Comment by indolering** [comment]
This has been going for nearly 2 weeks.  I made minor changes and I think it's ready to go.  Publish ACK?

**Comment by JeremyRand** [comment]
@indolering you didn't address @phelixbtc 's last comment (regarding full nodes, which I agree with).

**Comment by phelixbtc** [comment]
NACK.
I am quite certain there is still something wrong with the sentence I pointed out. @hlandau ?

@ryancdotorg :
  The last paragraph weakens the end of the article. It is only indirectly related to the issues discussed earlier and simply does not fit at the end. If it is meant to establish relevancy of the topic it should go at the beginning as part of the introduction.
  Also it does not make sense to give publicity and link to a project that you claim is dangerous. Once again, calling out specific projects sounds unprofessional to me and leaves a bad taste of personal motivation. Before we publicly bash someone in the same boat with us we should discuss it on the forum in any case.

**Comment by ryancdotorg** [comment]
I am currently working on making major changes.

**Comment by JeremyRand** [comment]
I'm fine with waiting for @ryancdotorg 's proposed changes.

**Comment by phelixbtc** [comment]
@ryancdotorg Please consider a separate blog post on the advantages and disadvantages of server based resolving. :)

**Comment by ryancdotorg** [comment]
@phelixbtc What about a list of ways to access .bit domains with objective pros/cons for each, maybe?

**Comment by ryancdotorg** [comment]
my changes are done, @indolering can you put them on github?

**Comment by ryancdotorg** [comment]
@JeremyRand @phelixbtc can you please proofread it once @indolering does that? It'd be good to get this posted today.

**Comment by indolering** [comment]
See [GDoc](https://docs.google.com/document/d/14TXZQCISAVBPXKV_iqGCFXyBR6Q7nJ7_KG3pik_G5PI/edit).

**Comment by indolering** [comment]
I've scheduled the blogpost to go live tomorrow.  If there are any changes from the current GDoc, just tag me in the reply and I will update the blogpost.

**Comment by JeremyRand** [comment]
The terminology is not settled; see https://github.com/hlandau/ncdocs/issues/2 .  I do not want to have to revise after posting.  Please DO NOT post until terminology is figured out.

**Comment by indolering** [comment]
@JeremyRand terminology settled, [ACK](https://docs.google.com/document/d/14TXZQCISAVBPXKV_iqGCFXyBR6Q7nJ7_KG3pik_G5PI/edit)?

**Comment by indolering** [comment]
Naming has been settled and altered, JBisch gave it a proofread, posted:

http://blog.namecoin.org/post/109811339625/lightweight-resolvers

Please close.

**Comment by phelixbtc** [comment]
@ryancdotorg I liked your edited version of the last paragraph.
