### ISSUE TITLE
Concerns Regarding Namecoin Blogpost

### ISSUE THREAD

**Issue by indolering** [namecoin/namecoin.info#90]
Jeremy had a discussion with a pair of Tor developers.  They had 4 major concerns that we have either addressed or have on our roadmap.  I would like to publish a blogpost which covers these concerns so that I can link to it from a grant application.

[Link](https://docs.google.com/document/d/1tTkhqL59sebklCy6zMtMKJG6ZQ2nba8-qXc3OFPTvQc/edit?usp=sharing)

**Comment by JeremyRand** [comment]
I've posted initial comments on that link.

**Comment by indolering** [comment]
@JeremyRand ACK?

**Comment by indolering** [comment]
ACKed by Jeremy over IRC.

**Comment by JeremyRand** [comment]
ACK confirmed.
